### PR TITLE
#7-MOSCOW

### PR DESCRIPTION
**Pull request by bubriks**

### CODE REVIEW

**Comment by RaidenRabit** [comment]
testing bot integration

**Review by RaidenRabit — COMMENTED** [review]
Looks ok, but its incomplete (missing images). Also, please follow the headers of the report (their size, numbers, style, etc.)

**Review by RaidenRabit — COMMENTED** [review]
Im ok with it, but @AdamBlazsek must review it as well 📦

**Review by AdamBlazsek — APPROVED** [review]
Looks good to me, one small typo, not will not do but won't do, idk if thats an issue or not

**Pull request merged**
